#!/usr/bin/env python3
from mako.template import Template
from os import chdir
from os.path import dirname, realpath

model_documentation_groups = ["test-group",
                              "CDA-Razavi",
                              "Cambridge-Trotter",
                              "Emory-Lopman",
                              "Harvard-Sweet",
                              "IC-Garske",
                              "IC-Hallett",
                              "JHU-Lessler",
                              "JHU-Tam-Hib_PCV",
                              "JHU-Tam-Rota",
                              "KPW-Jackson",
                              "LSHTM-Clark-Hib_PCV",
                              "LSHTM-Clark-Rota",
                              "LSHTM-Jit-HPV",
                              "LSHTM-Jit-Measles",
                              "Li",
                              "OUCRU-Clapham",
                              "PHE-Vynnycky",
                              "PSU-Ferrari",
                              "UND-Moore",
                              "UND-Perkins"]

model_documentation_template = """
jwt {
    path /model-documentation/2019/${name}
    allow ${name} true
    publickey /public_key.pem
}
"""


estimate_comparison_diseases = ["HepB",
                                "Hib",
                                "HPV",
                                "JE",
                                "Measles",
                                "MenA",
                                "PCV",
                                "Rota",
                                "Rubella",
                                "YF"]

estimate_comparison_template = """
jwt {
    path /estimate-comparison/201810/${name}
    allow ${name} true
    publickey /public_key.pem
}
"""


def expand_template(template, subs):
    rules = ""
    for s in subs:
        rules += Template(template).render(name=s)
    return rules


def generate_caddyfile(template_path, target_path):
    print("Templating from {} to {}".format(template_path, target_path))
    with open(template_path, 'r') as f:
        template = Template(f.read())
    jwt_rules = expand_template(model_documentation_template,
                                model_documentation_groups) + \
                expand_template(estimate_comparison_template,
                                estimate_comparison_diseases)
    with open(target_path, 'w') as f:
        f.write(template.render(jwt_rules=jwt_rules))


if __name__ == "__main__":
    # Set working directory to this script's dir
    chdir(dirname(realpath(__file__)))
    generate_caddyfile("Caddyfile.template", "Caddyfile")
